### ISSUE TITLE
Can't find images

### ISSUE THREAD

**Issue by kevinburke** [hlyford/nba-headshot-api#4]
When I start the server locally and navigate to `http://localhost:8000/players/curry/stephen`, I get the following error:

```
Error: ENOENT: no such file or directory, stat '/Users/kevin/src/github.com/hlyford/nba-headshot-api/images'
   at Object.fs.statSync (fs.js:907:18)
   at Finder.Base (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/fs-finder/lib/Base.js:32:15)
   at new Finder (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/fs-finder/lib/Finder.js:23:43)
   at Function.Finder.from (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/fs-finder/lib/Finder.js:34:15)
   at /Users/kevin/src/github.com/hlyford/nba-headshot-api/server/router.js:27:10
   at Layer.handle [as handle_request] (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/express/lib/router/layer.js:95:5)
   at /Users/kevin/src/github.com/hlyford/nba-headshot-api/node_modules/express/lib/router/index.js:277:22
```

It looks like this directory gets populated by `scraper.js`? But I can't run this either, unfortunately...

```
$ node scraper.js
module.js:472
    throw err;
    ^

Error: Cannot find module './url-info'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kevin/src/github.com/hlyford/nba-headshot-api/scraper.js:7:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by hlyford** [comment]
Hey @kevinburke I didn't know the permissions surrounding the images, so wanted to gitignore any sensitive info. The DOM structure on the site they are crawled will likely change pretty often anyway, so scraper.js is likely to become out of date.
